### ISSUE TITLE
TypeError: Cannot read property 'App' of undefined

### ISSUE THREAD

**Issue by vincentparrett** [zhenwenc/create-react-app#1]
new app created, yarn start works fine and editing the project in vscode works fine, no ts errors with regards to the css modules support.

Yarn build, I get a blank page and the above error in the chrome dev tools. The problem looks to be css modules related, the import of App.css is not working so types is undefined.

I have seen the exact same error with an app created using
create-react-app my-app --scripts-version=react-scripts-ts 
and then ejecting so I can add css-modules support. 

Any ideas?

**Comment by zhenwenc** [comment]
Hi @vincentparrett , I couldn't reproduce the issue. I just published `zc-react-scripts@1.2.1`, could you try again and let me know if the issue still occurs. If so, could you post the generated `App.css.d.ts` file.

Please note, the `eject` feature on `zc-react-scripts` may not work as I didn't spent time on testing this feature, because the whole idea of using `create-react-app` is "no build configuration" :-). Is there any particular postcss feature you want to use but its not supported?

**Comment by zhenwenc** [comment]
Sorry mate, I just noticed that I left the `App.js` file in the template which is from the original `create-react-app` project. Not sure if its the cause though. 

`zc-react-scripts@1.2.2-0` had removed the `App.js` file.

**Comment by vincentparrett** [comment]
That now creates a new problem
npm start 
[at-loader] ./src/App.test.tsx:5:1 
    TS2304: Cannot find name 'it'.
npm build - nothing happens
yarn build - same error as npm start, looks like jest is missing?

**Comment by zhenwenc** [comment]
Hmm.. try `rm -rf node_modules package-lock.json yarn.lock && npm install`. Also check whether `@types/jest` is specified as a dependency in `package.json`?

There is a mistake on the `init` script, where it will install the latest version of `@types/jest`, but we are still using an older version `jest@20.0.4`. It shouldn't be the cause of this issue, but better to update to `@types/jest@^20.0.4`.

**Comment by vincentparrett** [comment]
sorry to say that I moved on, went back to create-react-app-typescript, ejected and then modified the webpack configs to suite. I was hoping I wouldn't need to mess with webpack (not a fan, far too complicated) but in the end I got what I needed done.

**Comment by zhenwenc** [comment]
all good mate, as long as thing works :-)
